# Omakase Ruby styling for Rails
inherit_gem: {rubocop-rails-omakase: rubocop.yml}

plugins:
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: true

Minitest/MultipleAssertions:
  Enabled: false
