name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.2", "3.3", "3.4"]
        rails: ["rails-7.1", "rails-7.2", "rails-8.0", "rails-8.1"]
        postgres: ["16", "17", "18"]
    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: rails_snowflake_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y build-essential git libyaml-dev pkg-config wget ca-certificates lsb-release gnupg2
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /etc/apt/keyrings/postgresql.gpg
          echo "deb [signed-by=/etc/apt/keyrings/postgresql.gpg] http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y postgresql-client-${{ matrix.postgres }}

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install Appraisal gemfiles
        run: bundle exec appraisal install

      - name: Show environment
        run: |
          ruby -v
          bundle exec appraisal list
          psql --version

      - name: Prepare test database (migrate)
        env:
          RAILS_ENV: test
          PGUSER: postgres
          PGPASSWORD: postgres
        run: bundle exec appraisal ${{ matrix.rails }} rake db:migrate

      - name: Run tests
        env:
          RAILS_ENV: test
          PGUSER: postgres
          PGPASSWORD: postgres
        run: bundle exec appraisal ${{ matrix.rails }} rake
